DATA_PATH = "/Users/niladi/workspace/seminar-kdd/data"
MD_ONLY = f"{DATA_PATH}/2024-05-14/MDOnly"
MEDMENTION_PATH = f"{DATA_PATH}/2024-07-28/MDOnly"
DATASETS_PATH = f"{DATA_PATH}/datasets"
CLIT_RESULTS_PATH = f"{DATA_PATH}/clit_results"
